		.ORIG x3000
		LEA R1, NAME
		LD R3, NEGENTER
AGAIN2 		GETC
		OUT
		ADD R2, R0, R3
		BRz CONT
		STR R0, R1, #0
		ADD R1, R1, #1
		BR AGAIN2
CONT		AND R2, R2, #0	
		LEA R0, NAME
		PUTS
		HALT
NEGENTER	.FILL xFFF6	
NAME		.BLKW #20 	
		.END			